export const CODES = {
  // Auth
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  AUTH_MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
  AUTH_SESSION_REPLACED: 'AUTH_SESSION_REPLACED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_PROFILE_UPDATE_SUCCESS: 'AUTH_PROFILE_UPDATE_SUCCESS',
  AUTH_PASSWORD_CHANGE_SUCCESS: 'AUTH_PASSWORD_CHANGE_SUCCESS',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_INVALID_ID: 'USER_INVALID_ID',
  USER_CREATE_SUCCESS: 'USER_CREATE_SUCCESS',
  USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
  USER_DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
  USER_PASSWORD_RESET_SUCCESS: 'USER_PASSWORD_RESET_SUCCESS',
  USER_IMPORT_SUCCESS: 'USER_IMPORT_SUCCESS',
  USER_NO_FILE_UPLOADED: 'USER_NO_FILE_UPLOADED',
  USER_INVALID_FILE_STRUCTURE: 'USER_INVALID_FILE_STRUCTURE',
  USER_USERNAME_EXISTS: 'USER_USERNAME_EXISTS',
  USER_INVALID_PASSWORD: 'USER_INVALID_PASSWORD',

  // Department
  DEPARTMENT_NOT_FOUND: 'DEPARTMENT_NOT_FOUND',
  DEPARTMENT_INVALID_ID: 'DEPARTMENT_INVALID_ID',
  DEPARTMENT_IMPORT_SUCCESS: 'DEPARTMENT_IMPORT_SUCCESS',
  DEPARTMENT_NAME_EXISTS: 'DEPARTMENT_NAME_EXISTS',
  DEPARTMENT_HAS_USERS: 'DEPARTMENT_HAS_USERS',
  DEPARTMENT_HAS_SECTIONS: 'DEPARTMENT_HAS_SECTIONS',

  // Section
  SECTION_NOT_FOUND: 'SECTION_NOT_FOUND',
  SECTION_INVALID_ID: 'SECTION_INVALID_ID',
  SECTION_NAME_EXISTS: 'SECTION_NAME_EXISTS',
  SECTION_HAS_USERS: 'SECTION_HAS_USERS',

  // Generic Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',

  // Master Data
  MASTER_DATA_FETCH_DEPARTMENTS_FAILED: 'MASTER_DATA_FETCH_DEPARTMENTS_FAILED',
  MASTER_DATA_FETCH_SECTIONS_FAILED: 'MASTER_DATA_FETCH_SECTIONS_FAILED',
  MASTER_DATA_SEARCH_SECTIONS_FAILED: 'MASTER_DATA_SEARCH_SECTIONS_FAILED',
  MASTER_DATA_FETCH_USERS_FAILED: 'MASTER_DATA_FETCH_USERS_FAILED',
  MASTER_DATA_FETCH_USER_LOGS_FAILED: 'MASTER_DATA_FETCH_USER_LOGS_FAILED',
  MASTER_DATA_INVALID_DEPARTMENT_ID: 'MASTER_DATA_INVALID_DEPARTMENT_ID',

  // System
  SYSTEM_LOG_CLEANUP_SUCCESS: 'SYSTEM_LOG_CLEANUP_SUCCESS',
  SYSTEM_SETTINGS_UPDATE_SUCCESS: 'SYSTEM_SETTINGS_UPDATE_SUCCESS',
  SYSTEM_SETTINGS_NOT_FOUND: 'SYSTEM_SETTINGS_NOT_FOUND',
  SYSTEM_MAINTENANCE_ACTIVE: 'SYSTEM_MAINTENANCE_ACTIVE',

  // Common
  COMMON_SUCCESS: 'COMMON_SUCCESS',

  // Backup
  BACKUP_FILE_NOT_FOUND: 'BACKUP_FILE_NOT_FOUND',

  // Export
  EXPORT_ROW_LIMIT_EXCEEDED: 'EXPORT_ROW_LIMIT_EXCEEDED',

  // Import
  IMPORT_PROCESS_FAILED: 'IMPORT_PROCESS_FAILED',

  // Import — file-level validation
  IMPORT_FILE_NO_WORKSHEETS: 'IMPORT_FILE_NO_WORKSHEETS',
  IMPORT_FILE_EMPTY: 'IMPORT_FILE_EMPTY',
  IMPORT_FILE_NO_DATA_ROWS: 'IMPORT_FILE_NO_DATA_ROWS',
  IMPORT_FILE_MISSING_COLUMN: 'IMPORT_FILE_MISSING_COLUMN',
  IMPORT_FILE_INVALID: 'IMPORT_FILE_INVALID',

  // Import — department row validation
  IMPORT_DEPT_NAME_REQUIRED: 'IMPORT_DEPT_NAME_REQUIRED',
  IMPORT_DEPT_NAME_TOO_LONG: 'IMPORT_DEPT_NAME_TOO_LONG',

  // Import — section row validation
  IMPORT_SECTION_DEPT_REQUIRED: 'IMPORT_SECTION_DEPT_REQUIRED',
  IMPORT_SECTION_NAME_REQUIRED: 'IMPORT_SECTION_NAME_REQUIRED',
  IMPORT_SECTION_DEPT_NOT_FOUND: 'IMPORT_SECTION_DEPT_NOT_FOUND',
  IMPORT_SECTION_NAME_TOO_LONG: 'IMPORT_SECTION_NAME_TOO_LONG',

  // Import — user row validation
  IMPORT_USER_USERNAME_REQUIRED: 'IMPORT_USER_USERNAME_REQUIRED',
  IMPORT_USER_FIRST_NAME_REQUIRED: 'IMPORT_USER_FIRST_NAME_REQUIRED',
  IMPORT_USER_LAST_NAME_REQUIRED: 'IMPORT_USER_LAST_NAME_REQUIRED',
  IMPORT_USER_DEPT_ID_REQUIRED: 'IMPORT_USER_DEPT_ID_REQUIRED',
  IMPORT_USER_USERNAME_LENGTH: 'IMPORT_USER_USERNAME_LENGTH',
  IMPORT_USER_USERNAME_FORMAT: 'IMPORT_USER_USERNAME_FORMAT',
  IMPORT_USER_USERNAME_EXISTS: 'IMPORT_USER_USERNAME_EXISTS',
  IMPORT_USER_USERNAME_DUPLICATE: 'IMPORT_USER_USERNAME_DUPLICATE',
  IMPORT_USER_DEPT_ID_INVALID: 'IMPORT_USER_DEPT_ID_INVALID',
  IMPORT_USER_DEPT_NOT_FOUND: 'IMPORT_USER_DEPT_NOT_FOUND',
  IMPORT_USER_SECTION_ID_INVALID: 'IMPORT_USER_SECTION_ID_INVALID',
  IMPORT_USER_SECTION_NOT_FOUND: 'IMPORT_USER_SECTION_NOT_FOUND',
  IMPORT_USER_SECTION_DEPT_MISMATCH: 'IMPORT_USER_SECTION_DEPT_MISMATCH',
  IMPORT_USER_EMAIL_INVALID: 'IMPORT_USER_EMAIL_INVALID',
  IMPORT_USER_TEL_INVALID: 'IMPORT_USER_TEL_INVALID',
  IMPORT_UNKNOWN_ERROR: 'IMPORT_UNKNOWN_ERROR',

  // User Log
  USER_LOG_NOT_FOUND: 'USER_LOG_NOT_FOUND',
} as const

export type ErrorCode = (typeof CODES)[keyof typeof CODES]
